FROM oraclelinux:8

# Notes about sqlplus installation:
#
#     https://yum.oracle.com/repo/OracleLinux/OL8/oracle/instantclient21/x86_64/
#     yum search instantclient
#     oracle-instantclient-release-el8.x86_64 => Oracle Instant Client yum repository configuration
#     oracle-instantclient-sqlplus.x86_64 => Oracle Instant Client SQL*Plus package
#
# Notes about the C dev environment:
#
#     We must install the following packages:
#     - oracle-instantclient-basic.x86_64
#     - oracle-instantclient-devel.x86_64
#     - oracle-instantclient-tools.x86_64

RUN (yum update -y; \
    yum install -y openssh-server \
                   openssh-clients \
                   initscripts \
                   epel-release \
                   wget \
                   passwd \
                   tar \
                   crontabs \
                   net-tools \
                   hostname \
                   file \
                   sudo \
                   less \
                   dos2unix.x86_64 \
                   jq.x86_64 \
                   openssl-devel.x86_64 \
                   oracle-instantclient-release-el8.x86_64 \
                   which.x86_64 \
                   tree.x86_64 \
                   mlocate.x86_64 \
                   unzip; \
    yum install -y libnsl.x86_64 \
                   oracle-instantclient-basic.x86_64 \
                   oracle-instantclient-devel.x86_64 \
                   oracle-instantclient-sqlplus.x86_64 \
                   oracle-instantclient-tools.x86_64; \
    yum clean all)

# -----------------------------------------------------------------
# Install "screen"
# -----------------------------------------------------------------

RUN (wget -O /tmp/screen-4.6.2-12.el8.x86_64.rpm https://yum.oracle.com/repo/OracleLinux/OL8/developer/EPEL/x86_64/getPackage/screen-4.6.2-12.el8.x86_64.rpm)
RUN (rpm -ivh /tmp/screen-4.6.2-12.el8.x86_64.rpm)

# -----------------------------------------------------------------
# Install all tools for dev
# -----------------------------------------------------------------

RUN (dnf group install --with-optional --assumeyes "Development Tools")

# -----------------------------------------------------------------
# Update CMAKE. Use "cmake --version" to ckeck
# The new version of "cmake" is installed under "/usr/local/bin".
# The original version will still be under "/usr/bin".
# -----------------------------------------------------------------

WORKDIR /tmp
RUN (wget https://github.com/Kitware/CMake/releases/download/v3.24.3/cmake-3.24.3.tar.gz)
RUN (tar zxvf cmake-3.24.3.tar.gz)
WORKDIR /tmp/cmake-3.24.3
RUN (./bootstrap && gmake && make install)
WORKDIR /tmp
RUN (rm -rf /tmp/cmake-3.24.3 cmake-3.24.3.tar.gz)

# -----------------------------------------------------------------
# Create and configure users.
# -----------------------------------------------------------------

RUN (useradd dev)
RUN (echo 'dev:dev' | chpasswd)
RUN (echo 'root:root' | chpasswd)
RUN (echo "dev   ALL=(ALL)      NOPASSWD: ALL" >> /etc/sudoers)

# -----------------------------------------------------------------
# Configure SSH server.
# -----------------------------------------------------------------

RUN (ssh-keygen -A; \
     sed -i 's/UsePAM yes/#UsePAM yes/g' /etc/ssh/sshd_config; \
     sed -i 's/#PermitRootLogin yes/PermitRootLogin yes/' /etc/ssh/sshd_config; \
     sed -i 's/#PasswordAuthentication yes/PasswordAuthentication yes/' /etc/ssh/sshd_config)

RUN (mkdir -p /root/.ssh/; \
     echo "StrictHostKeyChecking=no" > /root/.ssh/config; \
     echo "UserKnownHostsFile=/dev/null" >> /root/.ssh/config)

ADD data/install_ssh_keys.sh /tmp
RUN (dos2unix /tmp/install_ssh_keys.sh)
RUN (chmod a+xr /tmp/install_ssh_keys.sh)

USER dev
RUN (/tmp/install_ssh_keys.sh)
USER root
RUN (/tmp/install_ssh_keys.sh)

# -----------------------------------------------------------------
# Download ODPI-C, compile and install it. Then configure the
# dynamic library linker.
# -----------------------------------------------------------------

USER dev
WORKDIR /home/dev
RUN (wget -O odpci.zip https://github.com/oracle/odpi/archive/refs/heads/main.zip)
RUN (unzip odpci.zip)
WORKDIR /home/dev/odpi-main
RUN (make)

USER root
RUN (make install)
RUN (echo "/usr/local/lib" > /etc/ld.so.conf.d/odpic.conf)
RUN (rm -f /etc/ld.so.cache)
RUN (ldconfig)

# -----------------------------------------------------------------
# Clean up
# -----------------------------------------------------------------

USER root
RUN (rm /tmp/install_ssh_keys.sh)
RUN (rm /tmp/screen-4.6.2-12.el8.x86_64.rpm)
RUN (rm /home/dev/odpci.zip)

# -----------------------------------------------------------------
# Start the SSH daemon.
# -----------------------------------------------------------------

# 22 for ssh server. 7777 for gdb server.
EXPOSE 22 7777
CMD ["/usr/sbin/sshd", "-D"]
