FROM oraclelinux:8

RUN (yum update -y; \
    yum install -y openssh-server \
                   openssh-clients \
                   initscripts \
                   epel-release \
                   wget \
                   passwd \
                   tar \
                   crontabs \
                   net-tools \
                   hostname \
                   file \
                   sudo \
                   less \
                   unzip; \
    yum clean all)

# -----------------------------------------------------------------
# Install "screen"
# -----------------------------------------------------------------

RUN (wget -O /tmp/screen-4.6.2-12.el8.x86_64.rpm https://yum.oracle.com/repo/OracleLinux/OL8/developer/EPEL/x86_64/getPackage/screen-4.6.2-12.el8.x86_64.rpm)
RUN (rpm -ivh /tmp/screen-4.6.2-12.el8.x86_64.rpm)

# -----------------------------------------------------------------
# Install all tools for dev
# -----------------------------------------------------------------

RUN (dnf group install --with-optional --assumeyes "Development Tools")

# -----------------------------------------------------------------
# Create and configure users.
# -----------------------------------------------------------------

RUN (useradd dev)
RUN (echo 'dev:dev' | chpasswd)
RUN (echo 'root:root' | chpasswd)
RUN (echo "dev   ALL=(ALL)      NOPASSWD: ALL" >> /etc/sudoers)

# -----------------------------------------------------------------
# Configure SSH server.
# -----------------------------------------------------------------

RUN (ssh-keygen -A; \
     sed -i 's/UsePAM yes/#UsePAM yes/g' /etc/ssh/sshd_config; \
     sed -i 's/#PermitRootLogin yes/PermitRootLogin yes/' /etc/ssh/sshd_config; \
     sed -i 's/#PasswordAuthentication yes/PasswordAuthentication yes/' /etc/ssh/sshd_config)

RUN (mkdir -p /root/.ssh/; \
     echo "StrictHostKeyChecking=no" > /root/.ssh/config; \
     echo "UserKnownHostsFile=/dev/null" >> /root/.ssh/config)

ADD data/install_ssh_keys.sh /tmp
RUN (chmod a+xr /tmp/install_ssh_keys.sh)

USER dev
RUN (/tmp/install_ssh_keys.sh)
USER root
RUN (/tmp/install_ssh_keys.sh)

# -----------------------------------------------------------------
# Clean up
# -----------------------------------------------------------------

RUN (rm /tmp/install_ssh_keys.sh)
RUN (rm /tmp/screen-4.6.2-12.el8.x86_64.rpm)

# -----------------------------------------------------------------
# Start the SSH daemon.
# -----------------------------------------------------------------

EXPOSE 22
CMD ["/usr/sbin/sshd", "-D"]
