FROM oraclelinux:8

# Notes about sqlplus installation:
#
#     https://yum.oracle.com/repo/OracleLinux/OL8/oracle/instantclient21/x86_64/
#     yum search instantclient
#     oracle-instantclient-release-el8.x86_64 => Oracle Instant Client yum repository configuration
#     yum search sqlplus
#     oracle-instantclient-sqlplus.x86_64 => Oracle Instant Client SQL*Plus package

RUN (yum update -y; \
    yum install -y openssh-server \
                   openssh-clients \
                   initscripts \
                   epel-release \
                   wget \
                   passwd \
                   tar \
                   crontabs \
                   net-tools \
                   hostname \
                   file \
                   sudo \
                   less \
                   dos2unix.x86_64 \
                   jq.x86_64 \
                   openssl-devel.x86_64 \
                   oracle-instantclient-release-el8.x86_64 \
                   unzip; \
    yum install -y oracle-instantclient-sqlplus.x86_64; \
    yum clean all)

# -----------------------------------------------------------------
# Install "screen"
# -----------------------------------------------------------------

RUN (wget -O /tmp/screen-4.6.2-12.el8.x86_64.rpm https://yum.oracle.com/repo/OracleLinux/OL8/developer/EPEL/x86_64/getPackage/screen-4.6.2-12.el8.x86_64.rpm)
RUN (rpm -ivh /tmp/screen-4.6.2-12.el8.x86_64.rpm)

# -----------------------------------------------------------------
# Install all tools for dev
# -----------------------------------------------------------------

RUN (dnf group install --with-optional --assumeyes "Development Tools")

# -----------------------------------------------------------------
# Update CMAKE (required for CLion). Use "cmake --version" to ckeck
# -----------------------------------------------------------------

WORKDIR /tmp
RUN (wget https://github.com/Kitware/CMake/releases/download/v3.25.1/cmake-3.25.1.tar.gz)
RUN (tar zcvf cmake-3.25.1.tar.gz)
WORKDIR /tmp/cmake-3.25.1
RUN (./bootstrap && gmake && make install)
WORKDIR /tmp
RUN (rm -rf /tmp/cmake-3.25.1 /tmp/cmake-3.25.1.tar.gz)

# -----------------------------------------------------------------
# Create and configure users.
# -----------------------------------------------------------------

RUN (useradd dev)
RUN (echo 'dev:dev' | chpasswd)
RUN (echo 'root:root' | chpasswd)
RUN (echo "dev   ALL=(ALL)      NOPASSWD: ALL" >> /etc/sudoers)

# -----------------------------------------------------------------
# Configure SSH server.
# -----------------------------------------------------------------

RUN (ssh-keygen -A; \
     sed -i 's/UsePAM yes/#UsePAM yes/g' /etc/ssh/sshd_config; \
     sed -i 's/#PermitRootLogin yes/PermitRootLogin yes/' /etc/ssh/sshd_config; \
     sed -i 's/#PasswordAuthentication yes/PasswordAuthentication yes/' /etc/ssh/sshd_config)

RUN (mkdir -p /root/.ssh/; \
     echo "StrictHostKeyChecking=no" > /root/.ssh/config; \
     echo "UserKnownHostsFile=/dev/null" >> /root/.ssh/config)

ADD data/install_ssh_keys.sh /tmp
RUN (dos2unix /tmp/install_ssh_keys.sh)
RUN (chmod a+xr /tmp/install_ssh_keys.sh)

USER dev
RUN (/tmp/install_ssh_keys.sh)
USER root
RUN (/tmp/install_ssh_keys.sh)

# -----------------------------------------------------------------
# Clean up
# -----------------------------------------------------------------

RUN (rm /tmp/install_ssh_keys.sh)
RUN (rm /tmp/screen-4.6.2-12.el8.x86_64.rpm)

# -----------------------------------------------------------------
# Start the SSH daemon.
# -----------------------------------------------------------------

# 22 for ssh server. 7777 for gdb server.
EXPOSE 22 7777
CMD ["/usr/sbin/sshd", "-D"]
